In [ ]:
#Tutorial 3 Data Science
#Question 1
import numpy as np
array1 = np.array([[1,2],[3,4]])
print(array1)

[[1 2]
 [3 4]]


In [ ]:
#Question2
array2 = np.random.random((3,4))
print(array2)

[[0.56662177 0.05526638 0.72372162 0.26528186]
 [0.93416159 0.42034623 0.20954565 0.72396683]
 [0.17422493 0.44351963 0.77182794 0.5048529 ]]


In [ ]:
#Question3
num_of_matrices = int(input("Enter number of matrices :"))
num_of_row_and_columns = int(input("Enter number of rows and colums :"))

def build_matrices(num_of_matrices,num_of_row_and_columns):
  ones_array3 = np.ones((num_of_row_and_columns,num_of_row_and_columns))
  zeros_array3 = np.zeros((num_of_row_and_columns,num_of_row_and_columns))
  for i in range(num_of_matrices):
    print(ones_array3)
    print(zeros_array3)
    break

arrays3 = build_matrices(num_of_matrices,num_of_row_and_columns)



Enter number of matrices :3
Enter number of rows and colums :4
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#Question4
def transpose_array():
  original_array = np.random.rand(6,3)
  transposed_array = original_array.T
  print("Original array :\n")
  print(original_array)
  print("\n")
  print("Transposed array :\n")
  print(transposed_array)

transpose_array()

Original array :

[[0.74872271 0.91164074 0.7352532 ]
 [0.92970197 0.17632757 0.67520132]
 [0.01511475 0.0541728  0.31244573]
 [0.84615679 0.98076795 0.66967942]
 [0.79303083 0.70531519 0.02045798]
 [0.50659719 0.08312145 0.00136814]]


Transposed array :

[[0.74872271 0.92970197 0.01511475 0.84615679 0.79303083 0.50659719]
 [0.91164074 0.17632757 0.0541728  0.98076795 0.70531519 0.08312145]
 [0.7352532  0.67520132 0.31244573 0.66967942 0.02045798 0.00136814]]


In [ ]:
#Question5
n = int(input("Enter n:"))
p = int(input("Enter p:"))
m = int(input("Enter m:"))

def dot_product(n,p,m):
  array_A = np.random.rand(n,p)
  array_B = np.random.rand(p,m)
  dot_product = array_A @ array_B
  return dot_product

dot_product = dot_product(n,p,m)
print(dot_product)

Enter n:3
Enter p:4
Enter m:5
[[0.88081853 0.93678043 1.01197777 0.39928198 1.11601884]
 [0.42383541 0.63036556 0.57381941 0.15100391 0.64656308]
 [0.53403664 0.90162508 0.84449669 0.39271776 0.83026012]]
